blank_issues_enabled: false
contact_links:
  - name: Security Report ğŸ›¡
    url: https://github.com/verdaccio/verdaccio/security/policy
    about: I want to report a security vulnerability
  - name: Chat ğŸ˜
    url: http://chat.verdaccio.org
    about: For a quick question you should do it through our community chat
