web:
  title: Verdaccio Local Dev
  mode: slim
  sort_packages: asc
  primary_color: #CCC

plugins: ../

auth:
  auth-memory:
    users:
      foo:
        name: test
        password: test  # pragma: allowlist secret
      bar:
        name: bar
        password: test  # pragma: allowlist secret

security:
  api:
    jwt:
      sign:
        expiresIn: 120d
        notBefore: 1
  web:
    sign:
      expiresIn: 100d
      notBefore: 1

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
  'vue':
    access: foo
    publish: foo
    unpublish: foo
  'jquery':
    access: $all
    publish: bar
    unpublish: bar
  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
middlewares:
  audit:
    enabled: true

logs:
- { type: stdout, format: pretty, level: trace }

